apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/PixelNyx/simple_nginx_test
    path: manifests
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
