apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/PixelNyx/simple_nginx_test
    path: manifests
    targetRevision: HEAD
  syncPolicy:
    automatedSyncs:
      prune: true  # Delete undefined resources
      selfHeal: true  # Autosyncs if drift detected
    syncOptions:
      - CreateNamespace=true
