apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: "https://github.com/PixelNyx/Practice.git"
    path: "argocd/nginx_example_app/argocd_app"
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
